# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Creates xcode project"
  lane :xcode do
    Dir.chdir("..") do
      sh "swift package generate-xcodeproj --xcconfig-overrides Configs/Debug.xcconfig"
    end
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
